name = "HExcelFinance"
uuid = "29c9baf6-d00a-45ae-a083-60b079d21fc5"
authors = ["Johnathan Bizzano <johnathan.bizzano@gmail.com>"]
version = "0.2.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[compat]
HTTP = "0.8"
JSON = "0.21.2"


